---
- name: Setup ElasticSearch
  hosts: _ES_1
  connection: ssh
  become: true
  become_user: pawan
  gather_facts: true
  tasks:
    - name: Download the zip and execute shell
      shell: sudo apt-get -y install wget unzip && wget https://raw.githubusercontent.com/Paws11/Automate/master/ES/es1.sh && chmod -R +x es1.sh && sudo ./es1.sh


- name: Setup ElasticSearch
  hosts: _ES_2
  connection: ssh
  become: true
  become_user: pawan
  gather_facts: true
  tasks:
    - name: Download the zip and execute shell
      shell: sudo apt-get -y install wget unzip && wget https://raw.githubusercontent.com/Paws11/Automate/master/ES/es2.sh && chmod -R +x es2.sh && sudo ./es2.sh

- name: Setup ElasticSearch
  hosts: _ES_3
  connection: ssh
  become: true
  become_user: pawan
  gather_facts: true
  tasks:
    - name: Download the zip and execute shell
      shell: sudo apt-get -y install wget unzip && wget https://raw.githubusercontent.com/Paws11/Automate/master/ES/es3.sh && chmod -R +x es3.sh && sudo ./es3.sh
